# 
# Author: Kelvin Kabute
# Last-updated: 2026-04-20

# Author: Kelvin Kabute
# Last-updated: 2026-04-20

from scripts.detect_agent_provenance import detect_text


def test_detect_simple_copilot():
    text = "# Generated by GitHub Copilot"
    agent, conf, evidence = detect_text(text)
    assert agent is not None
    assert conf > 0
