# 
# Author: Kelvin Kabute
# Last-updated: 2026-05-03

# 
# Author: Kelvin Kabute
# Last-updated: 2026-05-03

# Author: Kelvin Kabute
# Last-updated: 2026-04-20
"""Tests for the agent provenance detector."""

# Author: Kelvin Kabute
# Last-updated: 2026-04-20

import importlib


def _load_detector_module():
    return importlib.import_module("scripts.detect_agent_provenance")


def test_detect_simple_copilot():
    mod = _load_detector_module()
    detect_text = mod.detect_text
    text = "# Generated by GitHub Copilot"
    agent, conf, evidence = detect_text(text)
    assert agent is not None
    assert conf > 0
