# 
# Author: Kelvin Kabute
# Last-updated: 2026-04-20

"""Minimal agent provenance detector stub.

This lightweight detector is intentionally conservative: returns (agent, confidence, evidence).
It exists so pre-commit hooks and tests can import a deterministic function. Replace with
the full detector implementation as needed.
"""
from typing import Tuple, List


def detect_text(text: str) -> Tuple[str | None, float, List[str]]:
    """Detect whether `text` was likely generated by an agent.

    Returns a tuple `(agent, confidence, evidence)` where `agent` is a short
    string like 'copilot' or `None` when no agent is detected.
    """
    if not text:
        return None, 0.0, []

    indicators = []
    low = text.lower()
    if "generated by" in low or "assistant" in low or "copilot" in low:
        indicators.append("contains agent keywords")

    # short heuristic: code with many repeated comment lines may be generated
    if text.count('\n') > 0 and (text.count('```') > 0 or text.count('# ') > 5):
        indicators.append('suspicious comment pattern')

    if indicators:
        return "agent", 0.5, indicators
    return None, 0.0, []
