# 
# Author: Kelvin Kabute
# Last-updated: 2026-04-20

# 
# Author: Kelvin Kabute
# Last-updated: 2026-04-20

"""Heuristic agent provenance detector.

This detector uses lightweight, explainable heuristics to estimate whether a
piece of text (code or prose) was likely produced by an automated coding
assistant. It returns `(agent, confidence, evidence)` where `agent` is a short
string such as ``'copilot'`` or ``'assistant'`` when explicit markers are
found, otherwise ``None``. ``confidence`` is a float in [0.0, 1.0]. ``evidence``
is a list of short strings describing the observed signals.

This is intentionally conservative and deterministic; it is suitable for
pre-commit hooks and CI checks as a first-pass classifier.
"""
from typing import Tuple, List, Optional
import re


def _uniq_ratio(words: List[str]) -> float:
    if not words:
        return 1.0
    return len(set(words)) / len(words)


def detect_text(text: str) -> Tuple[Optional[str], float, List[str]]:
    """Detect likely agent provenance using simple heuristics.

    Args:
        text: input text or source code to analyze.

    Returns:
        (agent, confidence, evidence)
    """
    evidence: List[str] = []
    if not text:
        return None, 0.0, evidence

    low = text.lower()

    # 1) Explicit agent markers
    agent = None
    explicit_map = {
        "github copilot": "copilot",
        "copilot": "copilot",
        "openai": "openai",
        "gpt-": "openai",
        "as an ai": "assistant",
        "generated by": "assistant",
        "this code was generated": "assistant",
    }
    for marker, a in explicit_map.items():
        if marker in low:
            agent = a
            evidence.append(f"explicit marker: {marker}")

    # 2) Explanatory phrase patterns often found in generated text
    phrase_patterns = [
        "here is a function",
        "here is an example",
        "example usage",
        "this function",
        "the following",
        "returns the",
        "usage:",
    ]
    phrase_matches = sum(1 for p in phrase_patterns if p in low)
    if phrase_matches:
        evidence.append(f"explanatory phrases: {phrase_matches}")

    # 3) Repetitiveness / lexical diversity
    words = re.findall(r"\w+", low)
    uniq = _uniq_ratio(words)
    if uniq < 0.40:
        evidence.append(f"low-lexical-uniqueness:{uniq:.2f}")

    # 4) Comment density (comments per line)
    lines = max(1, text.count("\n") + 1)
    comment_tokens = low.count("# ") + low.count("//") + low.count("/*")
    comment_density = comment_tokens / lines
    if comment_density > 0.05:
        evidence.append(f"comment-density:{comment_density:.2f}")

    # 5) Code-like token signals (def/class/import/console.log)
    code_tokens = sum(1 for kw in ("def ", "class ", "import ", "function ", "console.log", "public static") if kw in low)
    if code_tokens:
        evidence.append(f"code-tokens:{code_tokens}")

    # 6) Long, overly-polished prose blocks in code files
    long_comment = any(len(par.strip()) > 180 for par in re.split(r"\n\s*\n", text))
    if long_comment:
        evidence.append("long-comment-block")

    # Compute a simple confidence score from signals
    score = 0.0
    # explicit marker gives a strong signal
    if agent is not None:
        score += 0.6
    # lexical diversity contributes
    score += max(0.0, (0.6 - uniq)) * 0.6
    # phrase matches and comment density add modestly
    score += min(0.2, 0.05 * phrase_matches)
    score += min(0.2, comment_density * 2.0)
    # code tokens and long comments add small amounts
    score += min(0.15, 0.05 * code_tokens)
    if long_comment:
        score += 0.05

    # clamp
    confidence = max(0.0, min(1.0, score))

    return agent, confidence, evidence


__all__ = ["detect_text"]

