#!/usr/bin/env python3
# Author: Kelvin Kabute
# Last-updated: 2026-04-20

"""
Lightweight heuristic detector for agent provenance.
Usage: python scripts/detect_agent_provenance.py [file1 file2 ...]
Outputs JSON lines with fields: path, agent, confidence, evidence
"""
import sys
import re
import json
from pathlib import Path

AGENT_PATTERNS = [
    (re.compile(r"Generated by GitHub Copilot", re.I), "github-copilot"),
    (re.compile(r"copilot", re.I), "github-copilot"),
    (re.compile(r"OpenAI|GPT[- ]?\d+|gpt-", re.I), "openai-gpt"),
    (re.compile(r"Claude|Anthropic", re.I), "anthropic-claude"),
    (re.compile(r"LLM-assisted|LLM assisted|AI-assisted|AI generated", re.I), "llm-assisted"),
]

FRONT_MATTER_KEYS = [re.compile(r"^author:\s*(.+)$", re.I | re.M), re.compile(r"^generated-by:\s*(.+)$", re.I | re.M)]


def detect_text(text: str):
    evidence = []
    agent_hits = {}
    # Check inline patterns
    for pat, name in AGENT_PATTERNS:
        if pat.search(text):
            evidence.append(pat.pattern)
            agent_hits[name] = agent_hits.get(name, 0) + 1

    # Check front-matter keys
    for keypat in FRONT_MATTER_KEYS:
        m = keypat.search(text)
        if m:
            val = m.group(1).strip()
            evidence.append(f"front-matter:{val}")
            # try to classify
            if "copilot" in val.lower():
                agent_hits["github-copilot"] = agent_hits.get("github-copilot", 0) + 1
            elif "openai" in val.lower() or "gpt" in val.lower():
                agent_hits["openai-gpt"] = agent_hits.get("openai-gpt", 0) + 1
            else:
                agent_hits["llm-assisted"] = agent_hits.get("llm-assisted", 0) + 1

    if not agent_hits:
        return None, 0.0, evidence

    # pick top agent
    top_agent = max(agent_hits.items(), key=lambda kv: kv[1])[0]
    # confidence is sigmoid-ish based on evidence count
    confidence = min(0.95, 0.2 + 0.25 * sum(agent_hits.values()))
    return top_agent, round(confidence, 2), evidence


def detect_file(path: Path):
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return {"path": str(path), "agent": None, "confidence": 0.0, "evidence": []}
    agent, confidence, evidence = detect_text(text)
    return {"path": str(path), "agent": agent, "confidence": confidence, "evidence": evidence}


def main(argv):
    paths = argv[1:] if len(argv) > 1 else ["."]
    results = []
    for p in paths:
        path = Path(p)
        if path.is_file():
            results.append(detect_file(path))
        else:
            for f in path.rglob("*"):
                if f.is_file():
                    results.append(detect_file(f))
    for r in results:
        print(json.dumps(r, ensure_ascii=False))


if __name__ == "__main__":
    main(sys.argv)
